config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root 'groups#index'
  resources :users, only: [:uodate]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    collection do
      get 'search'
    end
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :members
  has_many :users, through: :members
  has_many :messages

  def last_message
    if @message = self.messages.last
      if @message.body.present?
        return @message.body
      else
        return "画像が送信されました"
      end
    else
      return "まだメッセージはありません"
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true, unless: "image.present?"
  belongs_to :group
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :group_id, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :members
  has_many :groups, through: :members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @groups = current_user.groups
  end

  def new
   @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: "グループを作成しました"
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: "グループを編集しました"
    else
      flash.now[:alert] = "グループ名を入力してください"
      render :edit
    end
  end

  def search
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

    def set_group
     @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, user_ids: [])
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
 before_action :set_message_group

  def index
    @message = Message.new
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: "メッセージを送信しました" }
        format.json
      end
    else
      flash.now[:alert] = "メッセージを入力してください"
      render :index
    end
  end

  private

  def message_params
   params.require(:message).permit(:body, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end

  def set_message_group
    @groups = current_user.groups
    @group = Group.find(params[:group_id])
    @messages = Message.where(group_id: params[:group_id]).includes(:group)
  end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  def update
   current_user.update(update_params)
  end

  private

    def update_params
      params.require(:user).permit(:name, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      - @group.errors.full_messages.each do |message|
        %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "チャットメンバーを追加", class: "chat-group-form__label"
    .chat-group-form__field--right{id: "chat-member"}
      %input{class: "chat-group-form__input", id: "user-search-field", placeholder: "追加したいユーザー名を入力してください", type: "text"}
      = hidden_field_tag "group[user_ids][]", current_user.id
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right.chat-group-form__field--right--member
  .chat-group-form__field.clearfix
    .chat-group-form__field--right
      = f.submit 'SAVE', class: "chat-group-form__action-btn"

app/views/groups/_group.html.haml
= link_to group_messages_path(group), class: "group-link" do
  %p= group.name
  %span= group.last_message

app/views/groups/_sidebar.html.haml
.content__left
  .content__left__top
    = link_to edit_user_registration_path do
      %i.fa.fa-gear.fa-lg
    = link_to new_group_path do
      %i.fa.fa-edit.fa-lg
    %p= current_user.name
  .content__left__under
    = render @groups

app/views/groups/edit.html.haml
.chat-group-form
  %h1 グループの編集
  = render 'form'

app/views/groups/index.html.haml
.content
  = render 'sidebar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form'

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag :div, value, class: "flash flash__#{key}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_message.haml
.content__right__under__message__header
  .content__right__under__message__header__name
    = message.user.name
  .content__right__under__message__header__time
    = message.created_at.strftime("%Y/%m/%d %H:%M")
.content__right__under__message__content
  = content_tag :div, message.body, class: "content__right__under__message__content-text" if message.body.present?
  = image_tag message.image if message.image.present?

app/views/messages/_message.html.haml
.content__right__under__message__header
  .content__right__under__message__header__name{id: "message_count"}
    = message.user.name
  .content__right__under__message__header__time
    = message.created_at.strftime("%Y/%m/%d %H:%M")
.content__right__under__message__content{ "data-message-id": message.id }
  = content_tag :div, message.body, class: "content__right__under__message__content-text" if message.body.present?
  = image_tag message.image if message.image.present?

app/views/messages/index.html.haml
.content
  = render 'groups/sidebar'
  .content__right
    .content__right__top
      .content__right__top--left
        %p= @group.name
        .member Member：
        .members
          - @group.users.each do |user|
            = user.name
      .content__right__top--edit-btn
        = link_to "EDIT", edit_group_path(@group), class: "square_btn"
    .content__right__under
      .content__right__under__message{id: "message_area"}
        = render @messages
    .content__right__under--send-btn
      = form_for [@group,@message], html: { id: 'form' } do |f|
        = f.text_field :body, placeholder: "type a message", class: "message_form"
        = f.label :image do
          %i.fa.fa-image
        = f.file_field :image, class: "fileInput", style: "display:none;"
        = f.submit value: "SEND", class: "square_btn"